---
#
- name: create dbca response file
  template: src=dbca-11g.rsp.j2 dest=/tmp/dbca.rsp

- name: create database instance
  shell: "{{ oracle_database_oracle_home }}/bin/dbca -silent -responseFile /tmp/dbca.rsp >> /tmp/dbca.log"
  args:
    creates: "{{ oracle_database_oracle_home }}/dbs/spfile{{ oracle_database_sid }}.ora"
  register: command_result
  ignore_errors: yes

- debug:
    var: command_result

- name: fail if not success
  fail: msg="the command failed"
  when: "''100% complete' not in command_result.stdout_lines"

- name: add oratab
  template:
    src: oratab-11g.j2
    dest: /etc/oratab
    owner: oracle
    group: oinstall
  become: yes
  become_user: root

- name: set oracle sid
  lineinfile:
   dest: "/home/oracle/.bash_profile"
   regexp: "^{{ item.start }}"
   line: "{{ item.start }}{{ item.end }}"
   insertbefore: "export PATH"
  with_items:
   -
     start: "ORACLE_SID="
     end: "{{ oracle_database_sid }}"

   -
     start: "export ORACLE_SID"
     end: ""
