- name: validate oracle database instance is already created
  stat: path="{{ oracle_database_oracle_home }}/dbs/{{ oracle_database_sid }}.ora"
  register: ora
  become: yes

- debug:
    msg: "oracle database instance is already created with this name: {{ oracle_database_sid }}"
  when: ora.stat.exists

- set_fact:
    oracle_database_instance_already_created: yes
  when: ora.stat.exists
